vlado/earthquake-croatia

app/controllers/ads_controller.rb, app/models/ad.rb, app/views/ads/new.html.erb, config/locales/app.hr.yml, db/migrate/20201229233911_add_consent_to_ads.rb, db/schema.rb
This commit adds a consent to the ad model
=> Add consent checkbox

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/controllers/ads_controller.rb, app/models/ad.rb, app/views/ads/new.html.erb, config/initializers/bulma_errors.rb, config/locales/app.hr.yml, db/migrate/20201230143638_add_address_to_ads.rb, db/schema.rb, lib/tasks/auto_annotate_models.rake, test/fixtures/ads.yml, test/models/ad_test.rb
=> Add additional fields to ads

app/views/ads/index.html.erb
Address was added by @shime in https://github.com/vlado/earthquake-croatia/pull/11 originally
=> Display address on index page

app/views/ads/index.html.erb
=> Fix responsiveness of bulma tags in index

Gemfile, Gemfile.lock, app/controllers/ads_controller.rb, app/views/ads/new.html.erb
Closes #19.
As suggested by @berislavbabic.
=> Add honeypot for bots

Dockerfile, README.md, config/database.yml, docker-compose.yml, entrypoint.sh
=> Added docker-compose

app/controllers/ads_controller.rb, app/javascript/packs/application.js, app/models/ad.rb, app/views/ads/_ad.html.erb, app/views/ads/index.html.erb, app/views/ads/show.html.erb, app/views/layouts/application.html.erb, package.json, yarn.lock
- extracted ad template part into partial.
- Moved title/subtitle into layout
- added basic Ad show page with permalink
=> Implementing Ad permalinks mentioned in #17

app/helpers/ads_helper.rb, app/models/ad.rb, app/views/ads/_ad.html.erb, app/views/layouts/application.html.erb
Adding a nice icon which leads to the google maps url for the ad location.
=> Add a clickable google maps link to every post

app/models/ad.rb, app/views/ads/new.html.erb
We had someone playing and entering custom kinds. This should prevent
that.
=> Validate kind

app/views/ads/_ad.html.erb
=> ad: Make whole location clickable, fix color

app/javascript/controllers/clipboard_controller.js, app/javascript/controllers/filter_controller.js, app/javascript/controllers/google_analytics_controller.js, app/javascript/controllers/index.js, app/javascript/packs/application.js, app/views/ads/_ad.html.erb, app/views/ads/index.html.erb, app/views/layouts/application.html.erb, package.json, yarn.lock
=> Start using Stimulus

app/controllers/ads_controller.rb, app/views/ads/index.html.erb
=> Fix pagination

app/views/ads/_ad.html.erb
=> Fix tags markup

.github/workflows/lint.yml
Setup GitHub actions workflow to run Rubocop.
=> GitHub actions - lint workflow

app/views/ads/_ad.html.erb, app/views/ads/index.html.erb, app/views/ads/show.html.erb
Remove inline styles in favor of Bulma's helpers
=> Remove inline styles

Gemfile, Gemfile.lock
Closes #42
`SENTRY_DSN` env variable already added to heroku
=> Add Sentry for error tracking

README.md, app/views/layouts/application.html.erb
Closes https://github.com/vlado/earthquake-croatia/issues/39
=> Add statement to footer (hr) and readme (english)

Gemfile, Gemfile.lock, app/assets/images/map.svg, app/views/ads/_ad.html.erb, app/views/layouts/application.html.erb
=> Remove fontawesome in favor of inline svg

app/views/layouts/application.html.erb
=> Make hero a bit shorter so it doesn't take half the fold

README.md, app/helpers/ads_helper.rb, app/models/ad.rb
=> Add other ("Ostalo") service.

app/controllers/ads_controller.rb, app/helpers/ads_helper.rb, app/models/ad.rb, app/views/ads/_ad.html.erb, app/views/ads/index.html.erb, app/views/ads/new.html.erb, config/locales/app.hr.yml, db/migrate/20210103105959_rename_services_to_categories_and_make_them_enum.rb, db/schema.rb, test/fixtures/ads.yml, test/models/ad_test.rb
Since we are caling them categories I also renamed service to category.
2nd rename already :)
Now we have following categories:
Let me know what you think.
=> New categories (services).

app/assets/stylesheets/application.scss, app/javascript/controllers/clipboard_controller.js, package.json, yarn.lock
Closes #75 
We talked about this in #47.
=> Replace toastr with bulma-toast

app/assets/images/clipboard.svg, app/assets/images/dots-vertical.svg, app/assets/images/link.svg, app/assets/images/location.svg, app/assets/images/phone.svg, app/assets/stylesheets/application.scss, app/assets/stylesheets/utilities.scss, app/helpers/ads_helper.rb, app/helpers/application_helper.rb, app/javascript/controllers/card_dropdown_controller.js, app/views/ads/_ad.html.erb, app/views/ads/index.html.erb, app/views/ads/show.html.erb, app/views/layouts/application.html.erb
A couple of things I did. I think those provide a better UX/UI.
Open to suggestions to make this even better together.
- Put more emphasis on the tag (type of service)
- Make the address more visible
- Move the link to visualize on the map next to the address
- Reorganize CTAs button inside a dropdown
- Add icons
- Reduce container size on desktop so that texts aren't so long to read
I'm not fully satisfied with it but I think it's still better than what we currently have.
Looking forward to your opinions/suggestions.
This closes #36, I guess.
=> Redesign ad card

config/environments/production.rb
Sendgrid will stop working without API Key tomorrow.
https://sendgrid.com/docs/for-developers/sending-email/rubyonrails/
=> Switch to sendgrid api key

app/helpers/ads_helper.rb, app/views/ads/_form.html.erb
Closes https://github.com/vlado/earthquake-croatia/issues/127
=> Show selected city when editing ads

.github/workflows/verify.yml, .rubocop.yml, Gemfile, Gemfile.lock, README.md, app/controllers/ads_controller.rb, app/controllers/api/ads_controller.rb, app/helpers/ads_helper.rb, app/models/ad.rb, app/views/api/ads/index.json.jbuilder, config/routes.rb, spec/factories/ads.rb, spec/factories/cities.rb, spec/factories/counties.rb, spec/features/delete_an_ad_spec.rb, spec/features/post_an_ad_spec.rb, spec/rails_helper.rb, spec/requests/api/ads_request_spec.rb
This should allow other apps to use our data.
Related to https://github.com/vlado/earthquake-croatia/issues/112 and https://github.com/vlado/earthquake-croatia/issues/98
Response should look like this:
=> Basic API for ads
