vlado/earthquake-croatia

- app/views/ads/index.html.erb
- config/locales/hr.yml
This PR removes redundant city info from the index page and replaces timestamp with time ago.
> Show time ago instead of timestamp on index page

- app/helpers/ads_helper.rb
- app/models/ad.rb
- app/views/ads/index.html.erb
- app/views/ads/new.html.erb
- app/views/layouts/application.html.erb
Fixes https://github.com/vlado/earthquake-croatia/issues/8
Adds two new ad types:
- Prijava štete
- Usluge popravke
Also, disables analytics in anything other than production mode
How it looks like:
> New ad types, enable analytics only in production mode

- Procfile
Heroku detects the Rails app and adds proper web process but migrations
are not run on deploy/release.
> Procfile added

- Gemfile
- Gemfile.lock
- README.md
- db/seeds.rb
Added a simple seed data for easier local development.
I hope you don't mind that I used ffaker gem for lorem ipsum text (ad description) and I also added pry-rails gem for better rails console DX.
Let me know if I should remove it.
> Generate seed data for easier local development

- app/views/ads/index.html.erb
The long links in the page footer broke zoom on mobile.
Before:
After:
> Fix mobile view

- app/views/ads/new.html.erb
Checkbox field name is `:consent`, not `:consent_at`
> New ad: Fix clicking on checkbox label

- Gemfile
- Gemfile.lock
- config/environments/production.rb
We are redirecting all request to SSL in Cloudflare so we just need
to redirect eveything to www subdomain on app level
Closes https://github.com/vlado/earthquake-croatia/issues/37
> Redirect all traffic to www.potres-petrinja.hr and force ssl.

- app/models/ad.rb
- app/views/ads/_ad.html.erb
- app/views/layouts/application.html.erb
And I think it also looks better :)
@berislavbabic I notice that links with full address work fine on google maps so I just used that to simplify stuff.
> Show full address in one tag to save space on mobile.

- .gitignore
- Procfile.dev
- README.md
- app/models/ad.rb
- app/views/ads/_ad.html.erb
This PR https://github.com/vlado/earthquake-croatia/pull/79 broke the display of very long address on mobile.
This is a quick fix before the redesign.
> Fix long address display by spliting it to "address" and "zip and city"

- app/javascript/controllers/card_controller.js
- app/views/ads/index.html.erb
- app/views/layouts/_links.html.erb
- app/views/layouts/application.html.erb
Moves useful external links to the top as a by default uncollapsed card
How it looks after collapsing
> external-links: Move external links on top

- app/assets/stylesheets/application.scss
@vlado 
It was working fine on Firefox and I didn't check other browsers (mea culpa).
Should be good now.
> Fix SVG icon for Chrome and Safari

- app/views/ads/_ad.html.erb
Had some feedback on the full URL being shown out on each ad, proposing the above action menu style for consistency.
> Ad action menu style proposal 

- db/seeds.rb
Service field has been added to the Ad model with validations for it to be present within a range of specific values.
This PR updates the seed file so that it generates service field when generating ads.
> Fix seeds by adding service to the Ad generator

- app/views/layouts/_links.html.erb
This small fix allows for easier clicking anywhere on the whole "Vanjske poveznice s popisima ponude smještaja i prijevoza >"
not just the chevron ">" icon.
> Make the whole "Vanjske poveznice" title clickable

- db/migrate/20210103235304_add_index_to_kind_on_ads.rb
- db/schema.rb
- db/seeds.rb
@vlado we lost the index on kind due to this migration: https://github.com/vlado/earthquake-croatia/blob/master/db/migrate/20210101194804_rename_kind_to_service_on_ads.rb#L10
I'm adding it back in this PR as we're using that column to query the db when filtering:
https://github.com/vlado/earthquake-croatia/blob/master/app/controllers/ads_controller.rb#L8
> Add missing index on Ad.kind; Fix db:seeds

- Dockerfile
- Makefile
Setting up via the make route from README
didn't result in a working app due to two
reasons:
- JS dependencies were not installed
- make db-create failed because exec
doesn't start the container. Switching
to run fixes it and compessing to the
single rails command simplifies it.
> Fix Docker and Make setup

- app/models/ad.rb
- db/schema.rb
- test/fixtures/ads.yml
- test/models/ad_test.rb
Schema was pulled from one PR through testing
and accidentally merged with another PR which
broke db:setup rake task.
This corrects the schema to match the state of
master.
> Fix accidentally incorrect schema

- app/controllers/cities_controller.rb
The issue happened when user typed accented characters, for example "čak" for "Čakovec". We'd unaccent the city name in the database ("Cakovec"), but we didn't unaccent what user typed ("čak") and so there was no match between the two.
> Fix: City Search: Always remove accents before comparing names

- app/controllers/ads_controller.rb
- app/helpers/ads_helper.rb
- app/models/ad.rb
- app/models/concerns/softly_deletable.rb
- app/models/reason.rb
- app/views/ads/_ad.html.erb
- app/views/ads/delete/new.html.erb
- config/locales/app.hr.yml
- db/migrate/20210109210542_create_reasons.rb
- db/schema.rb
- db/seeds.rb
- spec/features/delete_an_ad_spec.rb
- spec/models/reason_spec.rb
Resolves: #117
Optionally, when deleting the ad the user can
select a reason from the dropdown and provide
a comment.
This is not shown anywhere in the app, it's for
us to analyse later.
> Add optional deletion reason

- spec/mailers/previews/ad_mailer_preview.rb
I was searching for this preview to link to it in one of the PRs, but couldn't find it so I remembered it was in `/test` directory and dug it up. :)
> Add back mailer preview for send_token

- app/controllers/ads/token_controller.rb
- app/mailers/ad_mailer.rb
- app/models/ad.rb
- app/services/ad_reminder.rb
- app/views/ad_mailer/send_reminder.text.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- db/migrate/20210114201454_add_reminder_fields_to_ad.rb
- db/schema.rb
- lib/tasks/ads.rake
- spec/factories/ads.rb
- spec/factories/cities.rb
- spec/factories/counties.rb
- spec/mailers/previews/ad_mailer_preview.rb
- spec/services/ad_reminder_spec.rb
Resolves: #121 
This adds a new reminder e-mail that reminds people
to edit or delete an ad to keep ads relevant.
The rake task is intended to be run by heroku scheduler
and it reminds only 300 oldest emails. That because
the e-mail plan we have supports 400 emails a day
on average and we don't want to eat the quota for other
emails. We have a backlog of unreminded e-mails and
the nighly job will just work through them over several
days.
> Add a reminder to be sent 2 days after ad creation
